### ISSUE TITLE
Operating reserve calculation

### ISSUE THREAD

**Issue by coopdanger** [IASA2/draft-ietf-iasa2-struct#35]
Was there WG discussion about this? It does not match what is in the LLC Agreement, Exhibit B. It should match -- we did the 2019 budget according to the agreement.

**Comment by jlivingood** [comment]
Ack - fixing now. The text was simply carried from 4071. Will align w/LLC Exhibit B.

Section now reads:

## Operating Reserve

An initial target operating reserve has been specified in Exhibit B of the {{IETF-LLC-A}}.  That says that the IETF LLC 
should maintain an operating reserve equal to the IETF LLC’s budgeted Net Loss for 2019 multiplied times three. The IETF 
LLC, in cooperation with ISOC, may regularly review the financial target for this reserve fund, as noted in the {{IETF-LLC-A}} or as otherwise necessary.

Should the IETF LLC generate an annual budget surplus, it may choose to direct all or part of the surplus towards 
the growth of the operating reserve.
